fred_api_key: '3dd37ba3122e1228a5bacd7f8c6f3775'

tickers: ['NVDA','JPM','WMT','TSLA','AMZN','AVGO','CAT','XOM','JNJ','ABT','PLD']
start_date: '2016-01-01'
interval: '1mo'
sp500_series_id: 'SP500'
frequency: 'm'

# output file
raw_stock_data: "data/raw/Stocks_2015_2025.csv"
raw_sp500_data: "data/raw/sp500_2015_2025.csv"
merged_data: "data/processed/merged_df.csv"
checksum_output: "data/processed/merged_df.sha"
plot_output: "data/processed/performance_chart.png" 

data_dirs:
  - "data/raw"
  - "data/processed"

  